database: postgres
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost/scs}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASS:zzh@scs.com}
  sql:
    init:
      mode: never
